# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20160909_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePicture',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
